# GitHub Pages Configuration
title: E2E-Commerce
description: Sistema completo de e-commerce desenvolvido com Node.js, Express e SQLite
baseurl: "/E2E-commerce"
url: "https://felipemacron.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/
  - node_modules/
  - package.json
  - package-lock.json
  - server.js
  - swagger.js
  - database.db
  - scripts/
  - controllers/
  - middleware/
  - models/
  - routes/
  - swagger-docs/
  - tests/

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
